### ISSUE TITLE
Announcement of acceptance/rejection 2025

### ISSUE THREAD

**Issue by alecadair** [sscs-ose/sscs-ose-code-a-chip.github.io#118]
Will winners for 2025 be announced soon? I have not heard anything about my submission being rejected or accepted. Even if rejected, it would be nice to know..

**Comment by msaligane** [comment]
We will release the results soon. One issue with your submission is that it is under the GPL3 license. Are you able to update it to apache 2.0? I think it is part of the competition guidelines.

**Comment by alecadair** [comment]
Yes, I will update that.

**Comment by alecadair** [comment]
@msaligane I changed the license to apache 2.0. I believe the submission guidelines originally stated any open source license would work, but I may be wrong. Thanks for the chance to update this.
