### ISSUE TITLE
rework example notebook

### ISSUE THREAD

**Issue by proppy** [sscs-ose/sscs-ose-code-a-chip.github.io#3]
It would be nice if the current example https://github.com/sscs-ose/sscs-ose-code-a-chip.github.io/blob/main/Notebooks/temp_sense_gencollab.ipynb only contained the required section header, so that people can more easily use it as a base template for their project.

It should also named as "example" or "template" to make it more explicit, it is documenting the base structure of the notebook.

**Comment by proppy** [comment]
Reworked the example notebook here:
https://colab.research.google.com/gist/proppy/4c441683a02dbb87004d449955102156/template_notebook_to_follow.ipynb#scrollTo=aKoPD8cKw2UL

**Comment by msaligane** [comment]
Thanks @proppy 
Can you send a PR here: https://github.com/sscs-ose/sscs-ose-chipathon.github.io

**Comment by proppy** [comment]
Done https://github.com/sscs-ose/sscs-ose-chipathon.github.io/pull/6
