### ISSUE TITLE
ISSCC23 "Code-a-Chip" submission still open?

### ISSUE THREAD

**Issue by developandplay** [sscs-ose/sscs-ose-code-a-chip.github.io#41]
Hi @msaligane,
I just saw @mithro post about this conference submission.

I was wondering if the application window is still open?
On the GitHub page and the IEEE page it is stated that the deadline is 3rd April.

It looks like on the GitHub page that there already are quite a few accepted submissions.
The "Note: Many thanks everyone for your participation! We recommend to resubmit your Notebooks to the next code-a-chip Notebook competition with revisions. Stay tuned!" part is confusing me a bit.

Are these accepted notebooks already invited for the conference or does it just mean they entered the program?
If so what differentiates the submitted (but not accepted) notebooks from the accepted ones?
Are there any issues to look out for that disqualified these notebooks?

Best wishes
Martin

**Comment by msaligane** [comment]
Hi Martin -

Yes, this is still open, and as you mentioned, the deadline is 3rd April. 
So please consider submitting your work.

The accepted notebooks are from the 1st edition of CAC at ISSCC'23. This call is for VLSI'23 in June.

Hope this helps.

**Comment by developandplay** [comment]
Oh I see. Thanks for the quick response.
Yes that indeed confused me.
It's great that the grant is being continued at another conference.

How do the two conferences/grants relate?
I'm guessing IEEE SSCS is the overaching organisation.

**Comment by msaligane** [comment]
No worries. How can we make it less confusing?

> How do the two conferences/grants relate?
> I'm guessing IEEE SSCS is the overaching organisation.

I am not sure I fully understand your question. But you are correct, this is through SCSS.

**Comment by developandplay** [comment]
Adding a section in the main readme about the past conference(s) and their accepted submissions would be helpful.
This would also give an additional idea about the scope and type of past projects.

I was just wondering if the grant aim, scope and audience was changed to fit each of these conferences or remained the same.

**Comment by msaligane** [comment]
Good idea. Thanks!

We did not change the scope. We would love to see more analog designs, though.
